name: Notify Vercel

on:
  push:
    branches:
      - main

jobs:
  vercel-status:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: notify vercel
        uses: vercel/repository-dispatch/actions/status@v1
        with:
          name: Vercel - resume: lint
